</div>
</td>
<td>
<div class="menutableright">
<?php
if (0) {#$_SESSION["sidebar_enabled"]) {
	print "<!-- menu is in the sidebar -->";
} else {
	print NewMenu();
}
  ?>
</div>
</td>
</tr>




<tr><td colspan="4">&nbsp;</td></tr>



<tr><td colspan="4">&nbsp;</td></tr>
</table>
<!--TOP TABLE ends-->

</td></tr>


<tr>
<td bgcolor="#000000" colspan=3><img height=1 alt="" src="images/transparent.png" width=1 border=0></td>
</tr>

<tr>
<td bgcolor="#000000"><img height=1 alt="" src="images/transparent.png" width=1 border=0></td>
<td style="background-color: #1d2088; padding:5px; text-align: right; "><a href="http://cinemasunshine.co.jp"><span style="padding:5px; color: #FFFFFF; font-size: 14px">CINEMA SUNSHINE</span></a></td>
<td bgcolor="#000000"><img height=1 alt="" src="images/transparent.png" width=1 border=0></td>
</tr>

<tr>
<td bgcolor="#000000" colspan=3><img height=1 alt="" src="images/transparent.png" width=1 border=0></td>
</tr>

<tr>
<td colspan=3><img height=3 alt="" src="images/transparent.png" width=1 border=0></td>
</tr>

<tr>
<td colspan=3>
&nbsp;
</td>
</tr>
</tbody>
</table>

</div>
</body></html>
