<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'Running in testmode, no emails will be sent. Check your config file.',
'The following restrictions have been set by your ISP:' => 'The following restrictions have been set by your ISP:',
'Script stage' => 'Script stage',
'Finished, Nothing to do' => '処理する内容がありません。',
'messages sent in' => 'メッセージにかかった時間',
'seconds' => 'seconds',
'invalid emails' => 'invalid emails',
'emails failed (will retry later)' => 'emails failed (will retry later)',
'emails unconfirmed (not sent)' => 'emails unconfirmed (not sent)',
'Warning: script never reached stage 5' => 'Warning: script never reached stage 5',
'This may be caused by a too slow or too busy server' => 'This may be caused by a too slow or too busy server',


'In safe mode, batches are set to a maximum of 100' => 'In safe mode, batches are set to a maximum of 100',
'Running in safe mode' => 'Running in safe mode',
'msgs/hr' => 'msgs/hr',
'Reload required' => 'Reload required',
'Finished, All done' => '全終了',
'Script finished, but not all messages have been sent yet.' => 'Script finished, but not all messages have been sent yet.',
'Finished this run' => '送信処理完了',
'(test)' => '(test)',
'Would have sent' => 'Would have sent',
'(test)' => '(test)',
'Would have sent' => 'Would have sent',
'Started' => '処理開始',
'Processing has been suspended by your ISP, please try again later' => 'Processing has been suspended by your ISP, please try again later',
'Sending in batches of' => 'Sending in batches of',
'emails' => 'emails',
'This batch will be' => 'This batch will be',
'emails, because in the last' => 'emails, because in the last',
'emails were sent' => 'emails were sent',
'Sending in batches of' => 'Sending in batches of',
'emails' => 'emails',
'In the last' => 'In the last',
'seconds more emails were sent' => 'seconds more emails were sent',
'than is currently allowed per batch' => 'than is currently allowed per batch',
'Sent in last run' => 'Sent in last run',
'Skipped in last run' => 'Skipped in last run',
'Processing has started,' => 'メッセージ送信処理スタート,',
'message(s) to process.' => 'メッセージを送信します。',
'It is safe to click your stop button now, report will be sent by email to' => '処理中には絶対にほかの操作をしないでください。下記のメールアドレスをしようします。',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Your webserver is running in "safe_mode". Please keep this window open. It may reload several times to make sure all messages are sent.',
'Reports will be sent by email to' => 'Reports will be sent by email to',
'Processing message' => '進行中のメッセージ',
'Message' => 'Message',
'is an RSS feed for' => 'is an RSS feed for',
'Looking for users' => 'ユーザ検索中',
'users apply for attributes, now checking lists' => 'users apply for attributes, now checking lists',
'No users apply for attributes' => 'No users apply for attributes',
'looking for users who can be excluded from this mailing' => 'looking for users who can be excluded from this processqueue run',
'Process Killed by other process' => 'Process Killed by other process',
'Found them' => '現在',
'to process' => 'ユーザが検索されました。',
'No users to process for this batch' => 'No users to process for this batch',
'batch limit reached' => 'batch limit reached',
'Process Killed by other process' => 'Process Killed by other process',
'Message I was working on has disappeared' => 'Message I was working on has disappeared',
'Sending' => 'Sending',
'It took' => '',
'seconds to send' => 'seconds to send',
'Failed sending to' => 'Failed sending to',
'Unconfirmed user' => 'Unconfirmed user',
'Not sending to' => 'Not sending to',
'already sent' => 'already sent',
'Processed' => '準備完了',
'out of' => 'のうち',
'Hmmm, No users found to send to' => 'Hmmm, No users found to send to',
'It took' => '',
'to send this message' => 'がかかります。',
'waiting for' => 'waiting for',
'to make sure we don\'t exceed our limit of' => 'to make sure we don\'t exceed our limit of',
'messages in' => 'messages in',

### new in 2.9.5
'Message Sending has started' => 'Message Sending has started',
'phplist has started sending the message with subject %s' => 'phplist has started sending the message with subject %s',
'to view the progress of this message, go to %s' => 'to view the progress of this message, go to %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.',
'Introducing extra delay to decrease throttle failures' => 'Introducing extra delay to decrease throttle failures',
'%s is currently over throttle limit of %d per %d seconds' => '%s is currently over throttle limit of %d per %d seconds',
'not sending to ' => 'not sending to ',
'Message Sending has finished' => 'Message Sending has finished',
'phplist has finished sending the message with subject %s' => 'phplist has finished sending the message with subject %s',

'Sending of this message has been suspended' => 'Sending of this message has been suspended',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'Less than batch size were sent, so reloading imminently',
'Waiting for %d seconds before reloading' => '',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to',

);

?>